name: Check codebase

on:
  push:
    branches:
      - feature/codepl
  workflow_dispatch:
    inputs:
      check_dependency:
        description: 'Perform dependency check?'
        required: true
        default: 'Yes'
        type: choice
        options:
          - Yes
          - No

jobs:
  check_codebase:
    runs-on: ubuntu-latest

    env:
      CLIMAX_API_KEY: ${{ secrets.CLIMAX_API_KEY}}
      NVD_API_KEY: ${{ secrets.NVD_API_KEY}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Lint and code quality check
        run: mvn checkstyle:check

      # This checks usually takes quite a long time to process and that is why I made it dependent on the
      # manual trigger under workflow_dispatch to increase workflow efficiency
      - name: Dependency check
        if: ${{ github.event.inputs.check_dependency == 'Yes' }} # Run only when input is 'true'
        run: mvn dependency-check:check -Dthreads=4

      - name: Unit tests
        run: mvn test -DskipTests

      - name: Build and package
        run: mvn clean package -DskipTests