name: Build and check docker image

on:
  push:
    branches:
      - feature/dockerpl

  workflow_dispatch:

jobs:
  build_and_check_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      - name: Build docker image
        run: docker build --progress=plain --no-cache -t climax:latest .

      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'climax:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
