name: Build and deploy image in the server

on:
  release:
    types:
      - created

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            climax:latest
            climax:${{ github.event.release.tag_name }}
          push: true
